packages:
  - "apps/*"
  - "packages/*"

linkWorkspacePackages: true

packageManagerStrict: false

preferWorkspacePackages: true

saveWorkspaceProtocol: false

shamefullyHoist: true

strictPeerDependencies: true
